// File: units/present_simple_cont.js
const UNIT_DATA = [
    // --- PRODUCTION (Fill-in-the-blanks) ---
    { type: 'prod', q: 'Look! It (snow) outside.', a: 'is snowing', pts: 10 },
    { type: 'prod', q: 'I (not / like) coffee very much.', a: 'do not like', pts: 10 },
    { type: 'prod', q: 'The sun (rise) in the east.', a: 'rises', pts: 5 },
    { type: 'prod', q: 'Hurry up! The bus (come).', a: 'is coming', pts: 10 },
    { type: 'prod', q: 'How often (you / go) to the gym?', a: 'do you go', pts: 10 },
    { type: 'prod', q: 'Listen! Somebody (play) the piano.', a: 'is playing', pts: 10 },
    { type: 'prod', q: 'I (think) you are right.', a: 'think', pts: 5 },
    { type: 'prod', q: 'What (you / do) at the moment?', a: 'are you doing', pts: 10 },
    { type: 'prod', q: 'Water (boil) at 100 degrees Celsius.', a: 'boils', pts: 5 },
    { type: 'prod', q: 'I (not / watch) TV very often.', a: 'do not watch', pts: 5 },
    { type: 'prod', q: 'Where is John? He (have) a shower.', a: 'is having', pts: 10 },
    { type: 'prod', q: 'She (want) to be a doctor.', a: 'wants', pts: 5 },
    { type: 'prod', q: 'The Earth (go) round the Sun.', a: 'goes', pts: 5 },
    { type: 'prod', q: 'They (not / stay) at a hotel this week.', a: 'are not staying', pts: 10 },
    { type: 'prod', q: 'It (rain) a lot in winter.', a: 'rains', pts: 5 },
    { type: 'prod', q: 'I (learn) English for my job.', a: 'am learning', pts: 10 },
    { type: 'prod', q: 'What time (the film / start)?', a: 'does the film start', pts: 10 },
    { type: 'prod', q: 'I (not / understand) this word.', a: 'do not understand', pts: 5 },
    { type: 'prod', q: 'Look! That man (try) to open your car.', a: 'is trying', pts: 10 },
    { type: 'prod', q: 'My parents (live) in a small village.', a: 'live', pts: 5 },
    { type: 'prod', q: 'You (work) hard today.', a: 'are working', pts: 10 },
    { type: 'prod', q: 'I (forget) her name every time.', a: 'forget', pts: 5 },
    { type: 'prod', q: 'Please be quiet. I (work).', a: 'am working', pts: 10 },
    { type: 'prod', q: 'What (you / cook) for dinner tonight?', a: 'are you cooking', pts: 10 },
    { type: 'prod', q: 'The shops (open) at 9:00 AM.', a: 'open', pts: 5 },
    { type: 'prod', q: 'We (usually / have) lunch at 1 PM.', a: 'usually have', pts: 5 },
    { type: 'prod', q: 'I (know) what you mean.', a: 'know', pts: 5 },
    { type: 'prod', q: 'He (always / lose) his keys!', a: 'is always losing', pts: 10 },
    { type: 'prod', q: 'My sister (speak) four languages.', a: 'speaks', pts: 5 },
    { type: 'prod', q: 'You (look) tired today.', a: 'look', pts: 5 },
    { type: 'prod', q: 'The river (flow) very fast today.', a: 'is flowing', pts: 10 },
    { type: 'prod', q: 'I (need) some help with this.', a: 'need', pts: 5 },
    { type: 'prod', q: 'Why (you / cry)? What happened?', a: 'are you crying', pts: 10 },
    { type: 'prod', q: 'Rice (not / grow) in cold climates.', a: 'does not grow', pts: 5 },
    { type: 'prod', q: 'I (wait) for my friend right now.', a: 'am waiting', pts: 10 },
    { type: 'prod', q: 'The bus (arrive) at 8:30 every day.', a: 'arrives', pts: 5 },
    { type: 'prod', q: 'Who (that man / shout) at?', a: 'is that man shouting', pts: 10 },
    { type: 'prod', q: 'I (believe) you.', a: 'believe', pts: 5 },
    { type: 'prod', q: 'Most people (learn) to swim when children.', a: 'learn', pts: 5 },
    { type: 'prod', q: 'I (read) a great book at the moment.', a: 'am reading', pts: 10 },

    // --- MCQ (Multiple Choice) ---
    { type: 'mcq', q: 'They ___ to the cinema every Friday.', a: 'go', options: ['go', 'are going', 'goes', 'going'], pts: 5 },
    { type: 'mcq', q: 'She ___ her homework right now.', a: 'is doing', options: ['is doing', 'does', 'do', 'doing'], pts: 5 },
    { type: 'mcq', q: 'I ___ any help at the moment.', a: 'don’t need', options: ['don’t need', 'am not needing', 'not need', 'doesn’t need'], pts: 5 },
    { type: 'mcq', q: 'What ___ your brother do for a living?', a: 'does', options: ['does', 'do', 'is', 'doing'], pts: 5 },
    { type: 'mcq', q: 'Wait! I ___ with you.', a: 'am coming', options: ['am coming', 'come', 'comes', 'coming'], pts: 5 },
    { type: 'mcq', q: 'The moon ___ around the Earth.', a: 'moves', options: ['moves', 'is moving', 'move', 'moving'], pts: 5 },
    { type: 'mcq', q: '___ you hearing that strange noise?', a: 'Are', options: ['Are', 'Do', 'Does', 'Is'], pts: 5 },
    { type: 'mcq', q: 'I ___ breakfast every morning at 7:00.', a: 'have', options: ['have', 'am having', 'has', 'having'], pts: 5 },
    { type: 'mcq', q: 'It ___ a lot in the summer here.', a: 'doesn’t rain', options: ['doesn’t rain', 'isn’t raining', 'don’t rain', 'not rain'], pts: 5 },
    { type: 'mcq', q: 'Listen! The birds ___.', a: 'are singing', options: ['are singing', 'sing', 'sings', 'singing'], pts: 5 },
    { type: 'mcq', q: 'I ___ what he is saying.', a: 'don’t understand', options: ['don’t understand', 'am not understanding', 'not understand', 'doesn’t understand'], pts: 5 },
    { type: 'mcq', q: 'We ___ for a walk today because it is cold.', a: 'are not going', options: ['are not going', 'don’t go', 'not go', 'goes not'], pts: 5 },
    { type: 'mcq', q: 'My friend ___ in London for a few weeks.', a: 'is staying', options: ['is staying', 'stays', 'stay', 'staying'], pts: 5 },
    { type: 'mcq', q: 'Vegetarians ___ meat.', a: 'don’t eat', options: ['don’t eat', 'are not eating', 'doesn’t eat', 'not eat'], pts: 5 },
    { type: 'mcq', q: '___ it raining outside right now?', a: 'Is', options: ['Is', 'Does', 'Do', 'Are'], pts: 5 },
    { type: 'mcq', q: 'I ___ to the radio every morning.', a: 'listen', options: ['listen', 'am listening', 'listens', 'listening'], pts: 5 },
    { type: 'mcq', q: 'She ___ very hard for her exams this week.', a: 'is working', options: ['is working', 'works', 'work', 'working'], pts: 5 },
    { type: 'mcq', q: 'How many languages ___ you speak?', a: 'do', options: ['do', 'are', 'does', 'doing'], pts: 5 },
    { type: 'mcq', q: 'I ___ my umbrella today because it is sunny.', a: 'am not carrying', options: ['am not carrying', 'don’t carry', 'not carry', 'doesn’t carry'], pts: 5 },
    { type: 'mcq', q: 'The train ___ at 10 PM tonight.', a: 'leaves', options: ['leaves', 'is leaving', 'leave', 'leaving'], pts: 5 },
    { type: 'mcq', q: 'Why ___ you looking at me like that?', a: 'are', options: ['are', 'do', 'does', 'is'], pts: 5 },
    { type: 'mcq', q: 'I ___ the answer to this question.', a: 'know', options: ['know', 'am knowing', 'knows', 'knowing'], pts: 5 },
    { type: 'mcq', q: 'He ___ a shower every single morning.', a: 'takes', options: ['takes', 'is taking', 'take', 'taking'], pts: 5 },
    { type: 'mcq', q: 'Where ___ they usually go on holiday?', a: 'do', options: ['do', 'are', 'does', 'is'], pts: 5 },
    { type: 'mcq', q: 'Look! The cat ___ the tree.', a: 'is climbing', options: ['is climbing', 'climbs', 'climb', 'climbing'], pts: 5 },
    { type: 'mcq', q: 'I ___ very tired today.', a: 'feel', options: ['feel', 'am feeling', 'feels', 'feeling'], pts: 5 },
    { type: 'mcq', q: 'The coffee ___ delicious.', a: 'tastes', options: ['tastes', 'is tasting', 'taste', 'tasting'], pts: 5 },
    { type: 'mcq', q: 'We ___ for a new apartment at the moment.', a: 'are looking', options: ['are looking', 'look', 'looks', 'looking'], pts: 5 },
    { type: 'mcq', q: 'Do you ___ in ghosts?', a: 'believe', options: ['believe', 'believing', 'believes', 'are believing'], pts: 5 },
    { type: 'mcq', q: 'The population of the world ___ very fast.', a: 'is rising', options: ['is rising', 'rises', 'rise', 'rising'], pts: 5 },
    { type: 'mcq', q: 'I ___ what you are talking about.', a: 'don’t see', options: ['don’t see', 'am not seeing', 'not see', 'doesn’t see'], pts: 5 },
    { type: 'mcq', q: 'Water ___ at 0 degrees.', a: 'freezes', options: ['freezes', 'is freezing', 'freeze', 'freezing'], pts: 5 },
    { type: 'mcq', q: '___ you enjoying the party?', a: 'Are', options: ['Are', 'Do', 'Does', 'Is'], pts: 5 },
    { type: 'mcq', q: 'I ___ an interesting project right now.', a: 'am doing', options: ['am doing', 'do', 'does', 'doing'], pts: 5 },
    { type: 'mcq', q: 'He ___ usually drive to work.', a: 'doesn’t', options: ['doesn’t', 'isn’t', 'don’t', 'not'], pts: 5 },
    { type: 'mcq', q: 'I ___ my dinner. Can I call you back?', a: 'am eating', options: ['am eating', 'eat', 'eats', 'eating'], pts: 5 },
    { type: 'mcq', q: 'This book ___ to me.', a: 'belongs', options: ['belongs', 'is belonging', 'belong', 'belonging'], pts: 5 },
    { type: 'mcq', q: 'Who ___ you waiting for?', a: 'are', options: ['are', 'do', 'is', 'does'], pts: 5 },
    { type: 'mcq', q: 'It ___ colder outside. Put on a coat.', a: 'is getting', options: ['is getting', 'gets', 'get', 'getting'], pts: 5 },
    { type: 'mcq', q: 'I ___ remember his name.', a: 'don’t', options: ['don’t', 'am not', 'doesn’t', 'not'], pts: 5 },

    // --- SCRAMBLE (Sentence Reconstruction) ---
    { type: 'scramble', q: 'Reorder the sentence:', a: 'I am working at home today', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'She does not like orange juice', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'Where are you going right now', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'He always plays football on Sundays', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'The sun is shining very brightly', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'I do not understand the question', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'What are they talking about now', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'We usually go to the beach', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'Is it raining in London today', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'I am reading a very good book', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'Does he speak English very well', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'They are having dinner at the moment', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'My sister works in a big bank', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'Look the cat is sleeping on sofa', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'I never drink milk with coffee', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'Are you listening to the radio', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'The train arrives at six o clock', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'She is wearing a beautiful blue dress', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'Why are you wearing a coat', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'I often go swimming in summer', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'He is not using the computer now', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'Do you want some more water', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'I am learning to drive this month', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'They do not live here anymore', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'How often do you wash your car', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'The water is boiling in the kitchen', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'I think that you are right', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'Wait for me I am coming', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'What does this word mean here', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'He is staying with friends lately', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'I do not remember her name', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'Are they waiting for the bus', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'She usually walks to the office', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'Listen someone is singing in garden', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'I am not feeling well today', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'Does it rain much in winter', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'We are looking for a hotel', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'I always wake up at seven', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'He is looking for a job', pts: 10 },
    { type: 'scramble', q: 'Reorder the sentence:', a: 'Why is the baby crying now', pts: 10 }

];
