// Filename: units/regular_past.js
const UNIT_DATA = [
    // --- 40 MCQs: FOCUS ON SPELLING (1pt) ---
    { type: "mcq", q: "We ___ for three hours yesterday.", options: ["stoppied", "stopped", "stoped"], a: "stopped", pts: 1 },
    { type: "mcq", q: "She ___ to London in 2010.", options: ["moved", "moveed", "movvid"], a: "moved", pts: 1 },
    { type: "mcq", q: "I ___ for my exams all night.", options: ["studyed", "studdied", "studied"], a: "studied", pts: 1 },
    { type: "mcq", q: "The children ___ in the park.", options: ["played", "plaied", "playyed"], a: "played", pts: 1 },
    { type: "mcq", q: "He ___ the trip last week.", options: ["planed", "planned", "plannied"], a: "planned", pts: 1 },
    { type: "mcq", q: "They ___ the door quietly.", options: ["closed", "closeed", "closied"], a: "closed", pts: 1 },
    { type: "mcq", q: "We ___ the heavy bags.", options: ["carred", "carried", "carryed"], a: "carried", pts: 1 },
    { type: "mcq", q: "I ___ my friend on Sunday.", options: ["phoned", "phoneed", "phonned"], a: "phoned", pts: 1 },
    { type: "mcq", q: "The bus ___ at the corner.", options: ["stoped", "stopped", "stoppied"], a: "stopped", pts: 1 },
    { type: "mcq", q: "She ___ her room yesterday.", options: ["tidied", "tidyed", "tiddyed"], a: "tidied", pts: 1 },
    { type: "mcq", q: "They ___ at the disco.", options: ["danced", "danceed", "dancied"], a: "danced", pts: 1 },
    { type: "mcq", q: "He ___ to get the job.", options: ["tryed", "tried", "trid"], a: "tried", pts: 1 },
    { type: "mcq", q: "We ___ about the problem.", options: ["chatted", "chated", "chattied"], a: "chatted", pts: 1 },
    { type: "mcq", q: "The dog ___ all night.", options: ["barkked", "barked", "barkied"], a: "barked", pts: 1 },
    { type: "mcq", q: "She ___ the kitchen.", options: ["cleaned", "cleanned", "cleanied"], a: "cleaned", pts: 1 },
    { type: "mcq", q: "I ___ to the radio.", options: ["listened", "listenned", "listenied"], a: "listened", pts: 1 },
    { type: "mcq", q: "We ___ the film.", options: ["watched", "watchied", "watchhed"], a: "watched", pts: 1 },
    { type: "mcq", q: "They ___ last year.", options: ["marryed", "marrid", "married"], a: "married", pts: 1 },
    { type: "mcq", q: "He ___ the window.", options: ["opened", "openned", "openied"], a: "opened", pts: 1 },
    { type: "mcq", q: "I ___ at the joke.", options: ["smilled", "smiled", "smileed"], a: "smiled", pts: 1 },
    { type: "mcq", q: "We ___ the hotel.", options: ["liked", "likked", "likeed"], a: "liked", pts: 1 },
    { type: "mcq", q: "She ___ the heavy door.", options: ["pushed", "pushhed", "pushied"], a: "pushed", pts: 1 },
    { type: "mcq", q: "They ___ for the bus.", options: ["waited", "waitted", "waitied"], a: "waited", pts: 1 },
    { type: "mcq", q: "He ___ a new phone.", options: ["wanted", "wantted", "wantied"], a: "wanted", pts: 1 },
    { type: "mcq", q: "I ___ my dinner.", options: ["finished", "finishied", "finishhed"], a: "finished", pts: 1 },
    { type: "mcq", q: "The cat ___ the mouse.", options: ["chased", "chaseed", "chassied"], a: "chased", pts: 1 },
    { type: "mcq", q: "We ___ in Budapest.", options: ["lived", "liveed", "livved"], a: "lived", pts: 1 },
    { type: "mcq", q: "She ___ the question.", options: ["answered", "answeryed", "answeried"], a: "answered", pts: 1 },
    { type: "mcq", q: "They ___ the mountain.", options: ["climbed", "climbbed", "climbied"], a: "climbed", pts: 1 },
    { type: "mcq", q: "He ___ a cake.", options: ["baked", "bakkeed", "bakied"], a: "baked", pts: 1 },
    { type: "mcq", q: "I ___ the flowers.", options: ["watered", "waterred", "wateried"], a: "watered", pts: 1 },
    { type: "mcq", q: "We ___ the game.", options: ["started", "startted", "startied"], a: "started", pts: 1 },
    { type: "mcq", q: "She ___ the gift.", options: ["wrapped", "wraped", "wrappied"], a: "wrapped", pts: 1 },
    { type: "mcq", q: "They ___ in the sea.", options: ["jogged", "joged", "joggied"], a: "jogged", pts: 1 },
    { type: "mcq", q: "He ___ the gold.", options: ["robbed", "robed", "robbied"], a: "robbed", pts: 1 },
    { type: "mcq", q: "I ___ the letter.", options: ["copied", "copyed", "coppyed"], a: "copied", pts: 1 },
    { type: "mcq", q: "We ___ the taxi.", options: ["hurried", "hurryed", "hurried"], a: "hurried", pts: 1 },
    { type: "mcq", q: "She ___ to the news.", options: ["replied", "replyed", "replyied"], a: "replied", pts: 1 },
    { type: "mcq", q: "They ___ about the test.", options: ["worried", "worryed", "worryied"], a: "worried", pts: 1 },
    { type: "mcq", q: "He ___ his clothes.", options: ["dried", "dryed", "dryied"], a: "dried", pts: 1 },

    // --- 40 GAP-FILLS (1pt) ---
    { type: "gap-fill", q: "I [arrive] ___ at the airport at 6:00.", a: "arrived", pts: 1 },
    { type: "gap-fill", q: "He [stop] ___ the car at the red light.", a: "stopped", pts: 1 },
    { type: "gap-fill", q: "They [study] ___ hard for the test.", a: "studied", pts: 1 },
    { type: "gap-fill", q: "We [dance] ___ all night at the party.", a: "danced", pts: 1 },
    { type: "gap-fill", q: "She [plan] ___ a surprise for him.", a: "planned", pts: 1 },
    { type: "gap-fill", q: "The baby [cry] ___ for its mother.", a: "cried", pts: 1 },
    { type: "gap-fill", q: "I [watch] ___ a movie on Netflix.", a: "watched", pts: 1 },
    { type: "gap-fill", q: "We [stay] ___ in a small hotel.", a: "stayed", pts: 1 },
    { type: "gap-fill", q: "He [try] ___ to open the window.", a: "tried", pts: 1 },
    { type: "gap-fill", q: "They [chat] ___ online for an hour.", a: "chatted", pts: 1 },
    { type: "gap-fill", q: "I [phone] ___ my mother at noon.", a: "phoned", pts: 1 },
    { type: "gap-fill", q: "We [tidy] ___ the house on Saturday.", a: "tidied", pts: 1 },
    { type: "gap-fill", q: "She [work] ___ until 8:00 PM.", a: "worked", pts: 1 },
    { type: "gap-fill", q: "The teacher [check] ___ the homework.", a: "checked", pts: 1 },
    { type: "gap-fill", q: "It [rain] ___ all day yesterday.", a: "rained", pts: 1 },
    { type: "gap-fill", q: "They [live] ___ in Spain for two years.", a: "lived", pts: 1 },
    { type: "gap-fill", q: "I [cook] ___ dinner for my friends.", a: "cooked", pts: 1 },
    { type: "gap-fill", q: "We [wait] ___ for the train.", a: "waited", pts: 1 },
    { type: "gap-fill", q: "She [smile] ___ at the camera.", a: "smiled", pts: 1 },
    { type: "gap-fill", q: "They [travel] ___ by bus.", a: "travelled", pts: 1 },
    { type: "gap-fill", q: "He [close] ___ the window.", a: "closed", pts: 1 },
    { type: "gap-fill", q: "We [carry] ___ the bags.", a: "carried", pts: 1 },
    { type: "gap-fill", q: "I [enjoy] ___ the concert.", a: "enjoyed", pts: 1 },
    { type: "gap-fill", q: "She [ask] ___ a question.", a: "asked", pts: 1 },
    { type: "gap-fill", q: "They [help] ___ the old man.", a: "helped", pts: 1 },
    { type: "gap-fill", q: "He [decide] ___ to stay home.", a: "decided", pts: 1 },
    { type: "gap-fill", q: "We [play] ___ tennis for an hour.", a: "played", pts: 1 },
    { type: "gap-fill", q: "I [listen] ___ to some music.", a: "listened", pts: 1 },
    { type: "gap-fill", q: "She [finish] ___ her book.", a: "finished", pts: 1 },
    { type: "gap-fill", q: "They [marry] ___ in June.", a: "married", pts: 1 },
    { type: "gap-fill", q: "He [climb] ___ the tree.", a: "climbed", pts: 1 },
    { type: "gap-fill", q: "We [want] ___ some ice cream.", a: "wanted", pts: 1 },
    { type: "gap-fill", q: "I [use] ___ the computer.", a: "used", pts: 1 },
    { type: "gap-fill", q: "She [hurry] ___ to the office.", a: "hurried", pts: 1 },
    { type: "gap-fill", q: "They [rob] ___ the bank.", a: "robbed", pts: 1 },
    { type: "gap-fill", q: "He [jog] ___ in the morning.", a: "jogged", pts: 1 },
    { type: "gap-fill", q: "We [copy] ___ the notes.", a: "copied", pts: 1 },
    { type: "gap-fill", q: "I [tidy] ___ my bedroom.", a: "tidied", pts: 1 },
    { type: "gap-fill", q: "She [phone] ___ her friend.", a: "phoned", pts: 1 },
    { type: "gap-fill", q: "They [arrive] ___ late.", a: "arrived", pts: 1 },

    // --- 40 TRANSLATIONS: FOCUS ON PRODUCTION (2pts) ---
    { type: "translation", q: "Tanult", a: "studied", pts: 2 },
    { type: "translation", q: "Megállt", a: "stopped", pts: 2 },
    { type: "translation", q: "Eldöntötte", a: "decided", pts: 2 },
    { type: "translation", q: "Dolgozott", a: "worked", pts: 2 },
    { type: "translation", q: "Tervezett", a: "planned", pts: 2 },
    { type: "translation", q: "Takarított", a: "cleaned", pts: 2 },
    { type: "translation", q: "Szeretett", a: "loved", pts: 2 },
    { type: "translation", q: "Próbált", a: "tried", pts: 2 },
    { type: "translation", q: "Nézett", a: "watched", pts: 2 },
    { type: "translation", q: "Sétált", a: "walked", pts: 2 },
    { type: "translation", q: "Sírt", a: "cried", pts: 2 },
    { type: "translation", q: "Használt", a: "used", pts: 2 },
    { type: "translation", q: "Segített", a: "helped", pts: 2 },
    { type: "translation", q: "Várt", a: "waited", pts: 2 },
    { type: "translation", q: "Beszélgetett (online)", a: "chatted", pts: 2 },
    { type: "translation", q: "Befejezett", a: "finished", pts: 2 },
    { type: "translation", q: "Utazott", a: "travelled", pts: 2 },
    { type: "translation", q: "Mosolygott", a: "smiled", pts: 2 },
    { type: "translation", q: "Érkezett", a: "arrived", pts: 2 },
    { type: "translation", q: "Játszott", a: "played", pts: 2 },
    { type: "translation", q: "Főzött", a: "cooked", pts: 2 },
    { type: "translation", q: "Hallgatott (pl. zenét)", a: "listened", pts: 2 },
    { type: "translation", q: "Maradt", a: "stayed", pts: 2 },
    { type: "translation", q: "Cipelt", a: "carried", pts: 2 },
    { type: "translation", q: "Megházasodott", a: "married", pts: 2 },
    { type: "translation", q: "Telefonált", a: "phoned", pts: 2 },
    { type: "translation", q: "Rendbetett", a: "tidied", pts: 2 },
    { type: "translation", q: "Táncolt", a: "danced", pts: 2 },
    { type: "translation", q: "Élt", a: "lived", pts: 2 },
    { type: "translation", q: "Bezárt", a: "closed", pts: 2 },
    { type: "translation", q: "Kérdezett", a: "asked", pts: 2 },
    { type: "translation", q: "Kedvelt", a: "liked", pts: 2 },
    { type: "translation", q: "Futott (kocogott)", a: "jogged", pts: 2 },
    { type: "translation", q: "Sietett", a: "hurried", pts: 2 },
    { type: "translation", q: "Válaszolt", a: "replied", pts: 2 },
    { type: "translation", q: "Aggódott", a: "worried", pts: 2 },
    { type: "translation", q: "Másolt", a: "copied", pts: 2 },
    { type: "translation", q: "Lopott (bankot)", a: "robbed", pts: 2 },
    { type: "translation", q: "Szárított", a: "dried", pts: 2 },
    { type: "translation", q: "Indított", a: "started", pts: 2 }
];
